on:
  push:
    branches:
      - master

name: Build and Release APK

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Create Release
        id: create_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v0.0.2', // Change this tag as needed
              name: 'Release v0.0.2', // Change this name as needed
              draft: false,
              prerelease: false
            });
            return release;

      - name: Upload Debug APK
        uses: ncipollo/release-action@v1
        with:
          tag: v0.0.2  # This must match the tag created in the Create Release step
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
